<?php
class Vivacity_Flikebox_Model_System_Config_Language
{
  public function toOptionArray()
  {
    return array(
      array('value' => 'af_ZA', 'label' =>'Afrikaans'),
      array('value' => 'sq_AL', 'label' => 'Albanian - shqiptar'),
      array('value' => 'eu_ES', 'label' =>'Basque - Euskal'),
      array('value' => 'ar_AR', 'label' =>'Arabic - العربية&#8236;'),
      array('value' => 'hy_AM', 'label' =>'Armenian - հայերեն'),
      array('value' => 'ay_BO', 'label' =>'Aymara'),
      array('value' => 'az_AZ', 'label' =>'Azeri'),
      array('value' => 'be_BY', 'label' =>'Belarusian - беларускі'),
      array('value' => 'bn_IN', 'label' =>'Bengali - বাংলা'),
      array('value' => 'bs_BA', 'label' =>'Bosnian - bosanski'),
      array('value' => 'bg_BG', 'label' =>'Bulgarian - Български'),
      array('value' => 'ca_ES', 'label' =>'Catalan - Català'),
      array('value' => 'ck_US', 'label' =>'Cherokee'),
      array('value' => 'hr_HR', 'label' =>'Croatian - Hrvatska'),
      array('value' => 'cs_CZ', 'label' =>'Czech - České'),
      array('value' => 'da_DK', 'label' =>'Danish - dansk'),
      array('value' => 'nl_NL', 'label' =>'Dutch - Nederlands'),
      array('value' => 'nl_BE', 'label' =>'Dutch (Belgi?)'),
      array('value' => 'en_GB', 'label' =>'English (UK)'),
      array('value' => 'en_PI', 'label' =>'English (Pirate)'),
      array('value' => 'en_UD', 'label' =>'English (Upside Down)'),
      array('value' => 'en_US', 'label' =>'English (US)'),
      array('value' => 'eo_EO', 'label' =>'Esperanto'),
      array('value' => 'et_EE', 'label' =>'Estonian - Eesti'),
      array('value' => 'fo_FO', 'label' =>'Faroese'),
      array('value' => 'tl_PH', 'label' =>'Filipino - Pilipino'),
      array('value' => 'fi_FI', 'label' =>'Finnish - Suomi'),
      array('value' => 'fr_CA', 'label' =>'French (Canada) - Français (Canada)'),
      array('value' => 'fr_FR', 'label' =>'Galician - Galego'),
      array('value' => 'ka_GE', 'label' =>'Georgian - ქართული'),
      array('value' => 'de_DE', 'label' =>'German - German'),
      array('value' => 'el_GR', 'label' =>'Greek - Ελληνική'),
      array('value' => 'gn_PY', 'label' =>'Guaran'),
      array('value' => 'gu_IN', 'label' =>'Gujarati - ગુજરાતી'),
      array('value' => 'he_IL', 'label' =>'Hebrew - עברית'),
      array('value' => 'hi_IN', 'label' =>'Hindi - हिन्दी'),
      array('value' => 'hu_HU', 'label' =>'Hungarian - magyar'),
      array('value' => 'is_IS', 'label' =>'Icelandic - íslenska'),
      array('value' => 'id_ID', 'label' =>'Indonesian'),
      array('value' => 'ga_IE', 'label' =>'Irish - Gaeilge'),
      array('value' => 'it_IT', 'label' =>'Italian - italiano'),
      array('value' => 'ja_JP', 'label' =>'Japanese - 日本の'),
      array('value' => 'jv_ID', 'label' =>'Javanese - Jawa'),
      array('value' => 'kn_IN', 'label' =>'Kannada - ಕನ್ನಡ'),
      array('value' => 'kk_KZ', 'label' =>'Kazakh'),
      array('value' => 'km_KmH', 'label' =>'Khmer - ភាសាខ្មែរ'),
      array('value' => 'tl_ST', 'label' =>'Klingon'),
      array('value' => 'ko_KR', 'label' =>'Korean - 한국어'),
      array('value' => 'ku_TR', 'label' =>'Kurdish'),
      array('value' => 'la_VA', 'label' =>'Latin'),
      array('value' => 'lv_LV', 'label' =>'Latvian - Latvijas'),
      array('value' => 'fb_LT', 'label' =>'Leet Speak'),
      array('value' => 'li_NL', 'label' =>'Limburgish'),
      array('value' => 'lt_LT', 'label' =>'Lithuanian - Lietuvos'),
      array('value' => 'mk_MK', 'label' =>'Macedonian - македонски'),
      array('value' => 'mg_MG', 'label' =>'Malagasy'),
      array('value' => 'ms_MY', 'label' =>'Malay - Melayu'),
      array('value' => 'ml_IN', 'label' =>'Maltese - Malti'),
      array('value' => 'mr_IN', 'label' =>'Marathi - मराठी'),
      array('value' => 'mn_MN', 'label' =>'Mongolian - Монгол Улсын'),
      array('value' => 'ne_NP', 'label' =>'Nepali - नेपाली'),
      array('value' => 'se_NO', 'label' =>'Northern S?mi'),
      array('value' => 'nb_NO', 'label' =>'Norwegian (bokmal)'),
      array('value' => 'nn_NO', 'label' =>'Norwegian (nynorsk)'),
      array('value' => 'ps_AF', 'label' =>'Pashto'),
      array('value' => 'fa_IR', 'label' =>'Persian - فارسی'),
      array('value' => 'pl_PL', 'label' =>'Polish - Polskie'),
      array('value' => 'pt_BR', 'label' =>'Portuguese (Brazil)'),
      array('value' => 'pt_PT', 'label' =>'Portuguese (Portugal)'),
      array('value' => 'pa_IN', 'label' =>'Punjabi - ਪੰਜਾਬੀ'),
      array('value' => 'qu_PE', 'label' =>'Quechua'),
      array('value' => 'ro_RO', 'label' =>'Romanian - română'),
      array('value' => 'rm_CH', 'label' =>'Romansh'),
      array('value' => 'ru_RU', 'label' =>'Russian - русский'),
      array('value' => 'sa_IN', 'label' =>'Sanskrit'),
      array('value' => 'sr_RS', 'label' =>'Serbian - Српска'),
      array('value' => 'zh_CN', 'label' =>'Simplified Chinese (China) - 简体中文（中国)'),
      array('value' => 'sk_SK', 'label' =>'Slovak - slovenský'),
      array('value' => 'sl_SI', 'label' =>'Slovenian - slovenščina'),
      array('value' => 'so_SO', 'label' =>'Somali'),
      array('value' => 'es_LA', 'label' =>'Spanish - Español'),
      array('value' => 'es_CL', 'label' =>'Spanish (Chile)'),
      array('value' => 'es_CO', 'label' =>'Spanish (Colombia)'),
      array('value' => 'es_MX', 'label' =>'Spanish (Mexico)'),
      array('value' => 'es_ES', 'label' =>'Spanish (Spain)'),
      array('value' => 'sv_SE', 'label' =>'Swedish - svenska'),
      array('value' => 'sy_SY', 'label' =>'Syriac'),
      array('value' => 'tg_TJ', 'label' =>'Tajik'),
      array('value' => 'ta_IN', 'label' =>'Tamil - தமிழ்'),
      array('value' => 'tt_RU', 'label' =>'Tatar'),
      array('value' => 'te_IN', 'label' =>'Telugu - తెలుగు'),
      array('value' => 'th_TH', 'label' =>'Thai - ไทย'),
      array('value' => 'zh_HK', 'label' =>'Traditional Chinese (Hong Kong)'),
      array('value' => 'zh_TW', 'label' =>'Traditional Chinese (Taiwan)'),
      array('value' => 'tr_TR', 'label' =>'Turkish - türk'),
      array('value' => 'uk_UA', 'label' =>'Ukrainian - Український'),
      array('value' => 'ur_PK', 'label' =>'Urdu - اردو'),
      array('value' => 'uz_UZ', 'label' =>'Uzbek'),
      array('value' => 'vi_VN', 'label' =>'Vietnamese - Việt'),
      array('value' => 'cy_GB', 'label' =>'Welsh - Cymraeg'),
      array('value' => 'xh_ZA', 'label' =>'Xhosa'),
      array('value' => 'yi_DE', 'label' =>'Yiddish - ייִדיש'),
      array('value' => 'zu_ZA', 'label' =>'Zulu'),
    );
  }
}
